# Generated by Django 3.0.2 on 2020-03-12 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('authentication', '0007_company_sms_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='county',
            field=models.CharField(default='Nairobi', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='is_reseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='authentication.Company'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_director',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
