# Generated by Django 3.0.2 on 2020-03-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20200312_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email_count',
            field=models.IntegerField(default=5),
        ),
    ]
