# Generated by Django 3.0.2 on 2020-04-29 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_resetpasswordtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumer_keys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
