# Generated by Django 3.0.2 on 2020-05-04 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_consumerkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerkey',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='authentication.Company'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='APIKeyActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('key', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=50)),
                ('method', models.CharField(max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_key_activities', to='authentication.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
