# Generated by Django 3.0.2 on 2020-05-06 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_auto_20200504_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerkey',
            name='name',
            field=models.CharField(default='wagwan', max_length=70, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apikeyactivity',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumer_key', to='authentication.ConsumerKey'),
        ),
        migrations.AlterField(
            model_name='consumerkey',
            name='key',
            field=models.CharField(db_index=True, max_length=300, unique=True),
        ),
    ]
