# Generated by Django 3.0.2 on 2020-05-08 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_auto_20200506_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_api_key_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='apikeyactivity',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='authentication.ConsumerKey'),
        ),
        migrations.AlterField(
            model_name='consumerkey',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consumer_keys', to=settings.AUTH_USER_MODEL),
        ),
    ]
