# Generated by Django 3.0.2 on 2020-02-05 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_auto_20200130_1154'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='smsgroup',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='smsgroup',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='smsgroup',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='smsgroup',
            name='updated_at',
        ),
    ]
