# Generated by Django 3.0.2 on 2020-02-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_groupmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmember',
            name='group',
        ),
        migrations.AddField(
            model_name='smsgroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='groups', to='sms.GroupMember'),
        ),
    ]
