# Generated by Django 3.0.2 on 2020-02-10 10:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_auto_20200207_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsgroup',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='smsrequest',
            name='recepients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=5),
        ),
    ]
