# Generated by Django 3.0.2 on 2020-02-10 20:37

import core.utils.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sms', '0006_auto_20200210_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmember',
            name='email',
        ),
        migrations.AddField(
            model_name='groupmember',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_members', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='phone',
            field=models.CharField(max_length=30, unique=True, validators=[core.utils.validators.validate_phone_number]),
        ),
    ]
