# Generated by Django 3.0.2 on 2020-02-12 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_company'),
        ('sms', '0007_auto_20200210_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmember',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='smsgroup',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='smsrequest',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='smstemplate',
            name='owner',
        ),
        migrations.AddField(
            model_name='groupmember',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_group_members', to='authentication.Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smsgroup',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_groups', to='authentication.Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smsrequest',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sms_requests', to='authentication.Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smstemplate',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_templates', to='authentication.Company'),
            preserve_default=False,
        ),
    ]
