# Generated by Django 3.0.2 on 2020-02-13 08:23

import core.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_company'),
        ('sms', '0008_auto_20200212_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='phone',
            field=models.CharField(max_length=30, validators=[core.utils.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='smsgroup',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together={('company', 'phone')},
        ),
        migrations.AlterUniqueTogether(
            name='smsgroup',
            unique_together={('company', 'name')},
        ),
    ]
