# Generated by Django 3.0.2 on 2020-02-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0009_auto_20200213_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smstemplate',
            name='message',
            field=models.CharField(max_length=800),
        ),
    ]
