# Generated by Django 3.0.2 on 2020-02-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0010_auto_20200225_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsrequest',
            name='sms_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='smsrequest',
            name='message',
            field=models.CharField(max_length=800),
        ),
    ]
