# Generated by Django 3.0.2 on 2020-03-24 21:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0013_auto_20200319_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailrequest',
            name='recepients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='smsrequest',
            name='recepients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None),
        ),
    ]
