# Generated by Django 3.0.2 on 2020-03-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0014_auto_20200324_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrequest',
            name='subject',
            field=models.CharField(default='blah', max_length=800),
            preserve_default=False,
        ),
    ]
