# Generated by Django 3.0.2 on 2020-03-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0015_emailrequest_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailrequest',
            name='group',
        ),
        migrations.RemoveField(
            model_name='smsrequest',
            name='group',
        ),
        migrations.AddField(
            model_name='emailrequest',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='email_groups', to='sms.EmailGroup'),
        ),
        migrations.AddField(
            model_name='smsrequest',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='sms_groups', to='sms.SMSGroup'),
        ),
    ]
