# Generated by Django 3.0.2 on 2020-04-29 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0016_auto_20200325_1426'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='emailrequest',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='smsrequest',
            managers=[
            ],
        ),
    ]
