# Generated by Django 2.2.12 on 2020-05-15 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_auto_20200508_0906'),
        ('sms', '0017_auto_20200429_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSBranding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='authentication.Company')),
            ],
        ),
    ]
