# Generated by Django 2.2.12 on 2020-05-26 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_auto_20200508_0906'),
        ('sms', '0018_smsbranding'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentSMS',
            fields=[
                ('message_id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=30)),
                ('status_code', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_sms', to='authentication.Company')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveredSMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('network_code', models.CharField(max_length=10)),
                ('network', models.CharField(max_length=30)),
                ('failure_reason', models.CharField(max_length=30, null=True)),
                ('retry_count', models.CharField(max_length=30, null=True)),
                ('sent_sms', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='sms.SentSMS')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
