# Generated by Django 3.0.2 on 2020-03-06 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0012_periodictask_expire_seconds'),
        ('authentication', '0007_company_sms_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_schedules', to='authentication.Company')),
                ('schedules', models.ManyToManyField(related_name='schedules', to='django_celery_beat.PeriodicTask')),
            ],
        ),
    ]
