# Generated by Django 3.0.2 on 2020-03-06 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_company_sms_count'),
        ('django_celery_beat', '0012_periodictask_expire_seconds'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedule',
            new_name='ScheduleRegistry',
        ),
    ]
