# Generated by Django 3.0.2 on 2020-03-02 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0007_company_sms_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price_limit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RechargeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('customer_number', models.CharField(max_length=20)),
                ('checkout_request_id', models.CharField(max_length=50)),
                ('response_code', models.CharField(max_length=20)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('result_code', models.IntegerField()),
                ('result_desc', models.CharField(max_length=100)),
                ('amount', models.IntegerField(null=True)),
                ('mpesa_receipt_number', models.CharField(max_length=20, null=True, unique=True)),
                ('transaction_date', models.DateTimeField(null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
