# Generated by Django 3.0.2 on 2020-03-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechargeplan',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rechargeplan',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
