# Generated by Django 3.0.2 on 2020-03-04 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20200302_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechargerequest',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
