# Generated by Django 3.0.2 on 2020-03-05 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_company_sms_count'),
        ('payment', '0003_rechargerequest_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechargeplan',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.Company'),
        ),
    ]
