# Generated by Django 3.0.2 on 2020-03-05 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_rechargeplan_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rechargeplan',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
