# Generated by Django 3.0.2 on 2020-03-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20200305_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rechargeplan',
            name='price_limit',
            field=models.IntegerField(unique=True),
        ),
    ]
