# Generated by Django 2.2.12 on 2020-09-04 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0009_auto_20200515_0310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='mpesa_receipt_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='result_code',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='result_desc',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_date',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_action',
            field=models.CharField(choices=[('brand_payment', 'brand_payment'), ('sms_topup', 'sms_topup'), ('email_topup', 'email_topup')], default='sms_topup', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='ref_no',
            field=models.CharField(default='grhyth', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RechargeRequest',
        ),
    ]
